spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  session:
    timeout: 2592000
    # session存储于redis
    store-type: redis
  application:
    name: hi-heart
  # redis配置
  redis:
    host: localhost
    port: 6379
    database: 0


server:
  servlet:
    context-path: /api
    session:
      cookie:
        # cookie过期时间 30天
        max-age: 2592000  # 30 * 24 * 60 * 60
        domain: localhost